name: dgs_tab
description: A polymer application that creates nicely printed ADA surveys from field notes.
dependencies:
  core_elements: '>=0.2.0 <0.3.0'
  paper_elements: '>=0.1.0 <0.3.0'
  polymer: '>=0.13.0 <0.14.0'
  quiver: any
  uuid: '>=0.4.0 <0.5.0'
transformers:
- polymer:
    entry_points: web/dgs_tab.html
